/**
 * export-to-sdk.ts
 * ─────────────────
 * Reads hardhat-deploy deployment artifacts and writes
 * packages/sdk/src/generated/<network>.ts with contract addresses + ABIs.
 *
 * Usage:
 *   pnpm exec tsx scripts/export-to-sdk.ts --network localhost
 *   pnpm exec tsx scripts/export-to-sdk.ts --network sepolia
 *
 * Pattern copied from Paychain (patriciaOrtuno28/Paychain-On-Chain-Payroll)
 */

import fs from "node:fs";
import path from "node:path";
import process from "node:process";

type DeploymentJson = { address?: string; abi?: unknown };
type ArtifactJson  = { contractName?: string; abi?: unknown };

function getArg(flag: string): string | undefined {
  const idx = process.argv.indexOf(flag);
  return idx === -1 ? undefined : process.argv[idx + 1];
}

function isHexAddress(x: unknown): x is `0x${string}` {
  return typeof x === "string" && /^0x[a-fA-F0-9]{40}$/.test(x);
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function safeTsIdentifier(name: string): string {
  const s = name.replace(/[^a-zA-Z0-9_$]/g, "_");
  return /^[a-zA-Z_$]/.test(s) ? s : `_${s}`;
}

function deepEqualJson(a: unknown, b: unknown): boolean {
  return JSON.stringify(a) === JSON.stringify(b);
}

function walkDir(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    entry.isDirectory() ? out.push(...walkDir(full)) : out.push(full);
  }
  return out;
}

const network             = getArg("--network") ?? "localhost";
const repoRoot            = path.resolve(process.cwd(), "..", "..");
const deploymentsDir      = path.join(process.cwd(), "deployments", network);
const artifactsContracts  = path.join(process.cwd(), "artifacts", "contracts");
const sdkGeneratedDir     = path.join(repoRoot, "packages", "sdk", "src", "generated");
const outFile             = path.join(sdkGeneratedDir, `${network}.ts`);

if (!fs.existsSync(deploymentsDir)) {
  throw new Error(
    `No deployments found for network="${network}".\n` +
    `Expected: ${deploymentsDir}\n` +
    `Run: pnpm deploy:${network === "localhost" ? "local" : network}`
  );
}

fs.mkdirSync(sdkGeneratedDir, { recursive: true });

// Chain ID
let chainId = 0;
const chainIdFile = path.join(deploymentsDir, ".chainId");
if (fs.existsSync(chainIdFile)) {
  const parsed = Number(fs.readFileSync(chainIdFile, "utf8").trim());
  if (Number.isFinite(parsed)) chainId = parsed;
}

// Deployed addresses + ABIs
const addresses: Record<string, `0x${string}`> = {};
const deployedAbis: Record<string, unknown>    = {};

for (const file of fs.readdirSync(deploymentsDir)
  .filter(f => f.endsWith(".json") && !f.startsWith("."))) {
  const json = JSON.parse(
    fs.readFileSync(path.join(deploymentsDir, file), "utf8")
  ) as DeploymentJson;
  const name = path.basename(file, ".json");
  if (!json.address || !isHexAddress(json.address) || !json.abi) continue;
  addresses[name]    = json.address;
  deployedAbis[name] = json.abi;
}

// Artifact ABIs (contracts not yet deployed on this network)
const artifactAbis: Record<string, unknown>   = {};
const artifactSrc: Record<string, string>     = {};

for (const file of walkDir(artifactsContracts)
  .filter(f => f.endsWith(".json") && !f.endsWith(".dbg.json"))) {
  try {
    const parsed = JSON.parse(fs.readFileSync(file, "utf8")) as ArtifactJson;
    if (!isObject(parsed) || typeof parsed.contractName !== "string" || !parsed.abi) continue;
    const { contractName, abi } = parsed;
    if (artifactAbis[contractName] !== undefined) {
      if (!deepEqualJson(artifactAbis[contractName], abi))
        console.warn(`⚠️  ABI conflict for "${contractName}", keeping ${artifactSrc[contractName]}`);
      continue;
    }
    artifactAbis[contractName] = abi;
    artifactSrc[contractName]  = path.relative(process.cwd(), file);
  } catch (err) {
    console.warn(`⚠️  Failed to parse ${file}:`, err);
  }
}

// Merge — deployed takes priority
const abis: Record<string, unknown> = { ...deployedAbis };
for (const [name, abi] of Object.entries(artifactAbis)) {
  if (abis[name] === undefined) abis[name] = abi;
}

const deployedNames = Object.keys(addresses).sort();
const abiOnlyNames  = Object.keys(abis).filter(n => !(n in addresses)).sort();

const ts = `/* AUTO-GENERATED FILE — DO NOT EDIT.
   Generated by packages/contracts/scripts/export-to-sdk.ts
   Network: ${network}  |  Run: pnpm contracts:export${network !== "localhost" ? `:${network}` : ""}
*/
import type { ContractAddresses } from "../types.js";

export const chainId = ${chainId} as const;

export const addresses = ${JSON.stringify(addresses, null, 2)} as const satisfies ContractAddresses;

export const abis = ${JSON.stringify(abis, null, 2)} as const;

export const deployedContractNames = ${JSON.stringify(deployedNames, null, 2)} as const;
export const abiOnlyContractNames  = ${JSON.stringify(abiOnlyNames, null, 2)} as const;

${deployedNames
  .map(n => `export const ${safeTsIdentifier(n)} = { address: addresses.${n}, abi: abis.${n} } as const;`)
  .join("\n")}
${abiOnlyNames
  .map(n => `export const ${safeTsIdentifier(n)}Abi = abis.${n};`)
  .join("\n")}
`;

fs.writeFileSync(outFile, ts, "utf8");

console.log(`✅ SDK generated: ${outFile}`);
console.log(`   Network:  ${network} (chainId: ${chainId})`);
console.log(`   Deployed: ${deployedNames.join(", ") || "(none)"}`);
console.log(`   ABI-only: ${abiOnlyNames.join(", ") || "(none)"}`);